mode: deployment
image:
  repository: ghcr.io/dynatrace/dynatrace-otel-collector/dynatrace-otel-collector
  tag: 0.45.0
livenessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
readinessProbe:
  httpGet:
    path: /
    port: 13133
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
command:
  name: dynatrace-otel-collector
extraEnvs:
- name: DT_API_TOKEN
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_API_TOKEN
- name: DT_ENDPOINT
  valueFrom:
    secretKeyRef:
      name: dynatrace-otelcol-dt-api-credentials
      key: DT_ENDPOINT
resources:
  requests:
    memory: 100Mi
  limits:
    memory: 512Mi
config:
  extensions:
    health_check:
      endpoint: "0.0.0.0:13133"
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
          cors:
            allowed_origins:
              - "http://*"
              - "https://*"
    filelog: null

  processors:
    cumulativetodelta: {}
    k8sattributes:
      extract:
        annotations:
          - tag_name: dt.cost.costcenter
            key: costCentre
            from: pod
          - tag_name: deployment.release_stage
            key: deployment.release_stage
            from: pod
          - tag_name: deployment.release_product
            key: product
            from: pod
          - tag_name: dt.owner
            key: ownedBy
            from: pod
          - tag_name: supportInfo
            key: supportInfo
            from: pod
      pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.name
          - from: resource_attribute
            name: k8s.namespace.name
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

    transform:
      error_mode: ignore
      trace_statements:
          - context: resource
            statements: &k8s-statements
              - set(attributes["k8s.workload.kind"], "job") where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.job.name"]) where IsString(attributes["k8s.job.name"])
              - set(attributes["k8s.workload.kind"], "cronjob") where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.cronjob.name"]) where IsString(attributes["k8s.cronjob.name"])
              - set(attributes["k8s.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
              - set(attributes["k8s.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
              - set(attributes["k8s.workload.kind"], "replicaset") where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where IsString(attributes["k8s.replicaset.name"])
              - set(attributes["k8s.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
              - set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
              - delete_key(attributes, "k8s.deployment.name")
              - delete_key(attributes, "k8s.replicaset.name")
              - delete_key(attributes, "k8s.statefulset.name")
              - delete_key(attributes, "k8s.daemonset.name")
              - delete_key(attributes, "k8s.cronjob.name")
              - delete_key(attributes, "k8s.job.name")
      log_statements:
        - context: resource
          statements:
            - set(attributes["dt.kubernetes.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
            - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
            - set(attributes["dt.kubernetes.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
            - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
            - set(attributes["dt.kubernetes.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
            - set(attributes["dt.kubernetes.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
            - set(attributes["dt.kubernetes.cluster.id"], attributes["k8s.cluster.uid"]) where IsString(attributes["k8s.cluster.uid"])
        - context: log
          statements:
            - set(attributes["k8s.workload.kind"], "job") where IsString(attributes["k8s.job.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.job.name"]) where IsString(attributes["k8s.job.name"])
            - set(attributes["k8s.workload.kind"], "cronjob") where IsString(attributes["k8s.cronjob.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.cronjob.name"]) where IsString(attributes["k8s.cronjob.name"])
            - set(attributes["k8s.workload.kind"], "daemonset") where IsString(attributes["k8s.daemonset.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.daemonset.name"]) where IsString(attributes["k8s.daemonset.name"])
            - set(attributes["k8s.workload.kind"], "statefulset") where IsString(attributes["k8s.statefulset.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.statefulset.name"]) where IsString(attributes["k8s.statefulset.name"])
            - set(attributes["k8s.workload.kind"], "replicaset") where IsString(attributes["k8s.replicaset.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.replicaset.name"]) where IsString(attributes["k8s.replicaset.name"])
            - set(attributes["k8s.workload.kind"], "deployment") where IsString(attributes["k8s.deployment.name"])
            - set(attributes["k8s.workload.name"], attributes["k8s.deployment.name"]) where IsString(attributes["k8s.deployment.name"])
            - delete_key(attributes, "k8s.deployment.name")
            - delete_key(attributes, "k8s.replicaset.name")
            - delete_key(attributes, "k8s.statefulset.name")
            - delete_key(attributes, "k8s.daemonset.name")
            - delete_key(attributes, "k8s.cronjob.name")
            - delete_key(attributes, "k8s.job.name")
            - set(attributes["alertmessage"], "Critical Redis connection error!")
              where resource.attributes["service.name"] == "cart"
              and resource.attributes["deployment.release_stage"] == "production"
              and IsMatch(body, "(?i)wasn't able to connect to redis.*")
            - set(attributes["priority"], "1")
              where resource.attributes["service.name"] == "cart"
              and resource.attributes["deployment.release_stage"] == "production"
              and IsMatch(body, "(?i)wasn't able to connect to redis.*")
      metric_statements:
          - context: resource
            statements: *k8s-statements

  exporters:
    debug:
      verbosity: detailed
    otlp_http:
      endpoint: "${env:DT_ENDPOINT}"
      headers:
        Authorization: "Api-Token ${env:DT_API_TOKEN}"

  service:
    extensions: [health_check]
    pipelines:
      traces:
        receivers: [otlp]
        processors: []
        exporters: [otlp_http]
      metrics:
        receivers: [otlp]
        processors: [cumulativetodelta]
        exporters: [otlp_http]
      logs:
        receivers: [otlp]
        processors: [k8sattributes, transform]
        exporters: [debug, otlp_http]
