site_name: "Dynatrace Observability Lab: Problem Detection with Logs"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace/obslab-log-problem-detection"
nav:
  - '1. About': index.md
  - '2. Getting Started': getting-started.md
  - '3. Installation Explained': installation-explained.md
  - '4. Access User Interface': access-ui.md
  - '5. Validate Observability Data': view-observability-data.md
  - '6. Build OpenPipeline Alert': build-openpipeline-alert.md
  - '7. Introduce System Change': introduce-change.md
  - '8. Review Problem': review-problem.md
  - '9. Cleanup': cleanup.md
  - '10. Resources': resources.md
  - "11. What's Next?": whats-next.md
theme:
  name: material
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default 
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
markdown_extensions:
  - attr_list
  - toc:
      permalink: '#'
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
plugins:
    - search
    - markdownextradata  
extra:
  dt:
    rumagent:
      snippet: <script type="text/javascript" src="https://js-cdn.dynatrace.com/jstag/145e12d594f/bf64904yne/1b109d4de75a8985_complete.js" crossorigin="anonymous"></script>
  obslab: obslab-log-problem-detection