opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
grafana:
  enabled: false
opensearch:
  enabled: false
prometheus:
  enabled: false

default:
  env:
    - name: OTEL_SERVICE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: "metadata.labels['app.kubernetes.io/component']"
    - name: OTEL_COLLECTOR_NAME
      value: 'dynatrace-collector-opentelemetry-collector'

components:
  cart:
    podAnnotations:
      ownedBy: teamA
      product: otel-demo-app
      costCentre: centre1
      environment: production
      supportInfo: |+
        ## Cart Service Issues Support Information
        If cart service is having issues, please contact the owner
        and review the [Ops runbook](FULL_APPS_URL_PLACEHOLDER/ui/document/DOCUMENT_ID_PLACEHOLDER)
